### ISSUE TITLE
Can't change color of an specific icon!!

### ISSUE THREAD

**Issue by bruna93** [ionic-team/ionicons#859]
This is the code i used to change the color in hover on css:
.logo-facebook:hover {
    color: #3b5998;
}

.logo-twitter:hover {
    color: #00aced;
}

.logo-google:hover {
    color: #dd4b39;
}

.logo-instagram:hover {
    color: #517fa4;
}

I also tried this:

icon-icon .logo-facebook:hover {
 color: blue
}

But nothing works. Please, help. Sorry for my poor english.

**Comment by modalton** [comment]
I'm experiencing this as well. Looks like the fills on most sharp/outline icons have color/fill hardcoded?

**Comment by bruna93** [comment]
Yes! I can chenge the color if i use "ion-icon" only, But this change the color of all icons. I can't change the color of an specific icon.

**Comment by bruna93** [comment]
Hi!!! The problem was solved. I created a class for each icon, and then I could to edit.

**Comment by samandeggs** [comment]
This is not ideal, I am experiencing the same issue with 5.1.2 via script tag. The example I have is with `logo-facebook` using inline styles on the path, as with `logo-instagram` it is rendered fine with:

`
ion-icon {
 color: #fff;
}
`

**Comment by Adeeb725** [comment]
@bruna93 

I still can't figure out how to do it for the Instagram logo, even with creating classes for each logo. Would you mind sharing your style markup?

**Comment by samandeggs** [comment]
> @bruna93
> 
> I still can't figure out how to do it for the Instagram logo, even with creating classes for each logo. Would you mind sharing your style markup?

Hey - I was only able to do this via importing the scripts via this method:

```<script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
	<script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>```

And then you can use the standard css rule of `ion-icon { color: #fff; }` or to a custom class that is associated with the `ion-icon` component. This is how I managed to get it working for the instagram logo specifically.

**Comment by brandyscarney** [comment]
Thanks for the issue! You can target the `name` property in CSS to style by a specific icon, or add a class to the `ion-icon`. Example code:

```css
ion-icon[name='logo-facebook'] {
  color: blue;
}

ion-icon.instagram {
  color: red;
}
```

Here is a Stackblitz example: https://stackblitz.com/edit/db6cly?file=index.html

I am going to close this as it seems to be working in the latest version of Ionicons but please provide a code reproduction if you are still running into issues, thank you!
